#!/usr/bin/env bash


TOPIC_RAW_FLIGHT_DATA="aviation-in"
TOPIC_FLIGHT_DATA_WITH_LANDED_TIME="in-air-with-landed-time"
TOPIC_AIRPORT="airport"
TOPIC_LANDED="landed"
MONGODB_COLL_FLIGHT_DATA_WITH_LANDED_TIME="landed20190203_08_00"

