version: '3.5'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
  kafka1:
    image: confluentinc/cp-kafka:5.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29091,PLAINTEXT_HOST://${HOST_NAME}:9092
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper
  kafka2:
    image: confluentinc/cp-kafka:5.1.0
    ports:
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29092,PLAINTEXT_HOST://${HOST_NAME}:9093
      KAFKA_BROKER_ID: 2
    depends_on:
      - zookeeper
  kafka3:
    image: confluentinc/cp-kafka:5.1.0
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:29093,PLAINTEXT_HOST://${HOST_NAME}:9094
      KAFKA_BROKER_ID: 3
    depends_on:
      - zookeeper
  mongodb:
    image: mongo:4.0.5
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
     - "27017:27017"
    volumes:
     - /Users/bwardzinski/volume/aviation/mongodb:/data/db
  kafka-connect:
    image: confluentinc/cp-kafka-connect:5.1.0
    ports:
      - "8083:8083"
    volumes:
     - /Users/bwardzinski/volume/aviation/kafka-connect-plugins:/plugins
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka1:29091,kafka2:29092,kafka3:29093
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "aviation-connect"
      CONNECT_CONFIG_STORAGE_TOPIC: "aviation-connect-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "aviation-connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "aviation-connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: ${HOST_NAME}
#      CONNECT_LOG4J_ROOT_LOGLEVEL: DEBUG
      CONNECT_PLUGIN_PATH: /usr/share/java,/plugins
      CONNECT_REST_HOST_NAME: "kafka-connect"
    depends_on:
     - zookeeper
     - kafka1
     - kafka2
     - kafka3

